name: Ensure Code Quality

on:
  workflow_dispatch:
  workflow_call:

permissions: {}

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  run-pre-commit-hooks:
    permissions:
      contents: read
    name: Build & Run Pre Commit hooks to verify code structure, quality etc. from pre-commit hooks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install pre-commit
        run: uv sync --only-group dev -v

      - name: Run pre-commit
        run: SKIP=trufflehog,no-commit-to-branch uv run pre-commit run --all-files --verbose
